# -*- coding: utf-8 -*-
"""Code03-02

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RmhNdIhaJtNwN5ktbsAiMmZ1aMgqsl_6
"""

#Code03-02.py
print("\n줄바꿈\n연습 ")
print("\t탭키\t연습")
print("글자가 \"강조\"되는 효과1")
print("글자가 \'강조\'되는 효과2")
print("\\\\\\ 역슬래시 세 개 출력")
print(r"\n \t \" \\를 그대로 출력")