# -*- coding: utf-8 -*-
"""20250318-python의 사본

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RmhNdIhaJtNwN5ktbsAiMmZ1aMgqsl_6
"""

#Code03-01.py

print("%d" % 123)
print("%5d" % 123)
print("%05d" % 123)

print("%f" % 123.45)
print("%7.1f" % 123.45)
print("%7.3f" % 123.45)

print("%s" % "Python")
print("%10s" % "Python")