# -*- coding: utf-8 -*-
"""python과제0327.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_F6cFUvkWHf19z19uymvd6mRHKyQXCzb
"""
#Code02-05.py
import turtle

turtle.shape('turtle')

turtle.forward(200)
turtle.right(90)
turtle.forward(200)
turtle.right(90)
turtle.forward(200)
turtle.right(90)
turtle.forward(200)

turtle.done()
