# -*- coding: utf-8 -*-
"""20250311-python.ipynb의 사본

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1afHadLGz4KWUsKG773IyN537BSZOV3T7
"""

#Code02-07.py
import turtle
import random

##함수선언
def screenLeftClick(x,y):
  global r,g,b
  turtle.pencolor((r,g,b))
  turtle.pendown()
  turtle.goto(x,y)

def screenRightClick(x,y):
  turtle.penup()
  turtle.goto(x,y)

def screenMidClick(x,y):
  global r,g,b
  tSize= random.randrange(1,10)
  turtle.shapesize(tSize)
  r=random.random()
  g=random.random()
  b=random.random()

##변수선언
pSize = 10
r,g,b = 0.0, 0.0, 0.0

##메인코드
turtle.title("거북이로 그림 그리기")
turtle.shape("turtle")
turtle.pensize(pSize)

turtle.onscreenclick(screenLeftClick,1)
turtle.onscreenclick(screenMidClick,2)
turtle.onscreenclick(screenRightClick,3)

turtle.done()

