# -*- coding: utf-8 -*-
"""20250320-python

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12WR9gD28ObaHK40aHSyWzDMtz2S04Gb0
"""

#Code04-01.py

#변수 선언
money, c500, c100, c50, c10 = 0, 0, 0, 0, 0

#메인코드
money = int(input("교환할 돈은 얼마? "))

c500 = money // 500
money %= 500

c100 = money // 100
money %= 100

c50 = money // 50
money %= 50

c10 = money // 10
money %= 10

print("\n 500원짜리 ==> %d개" %c500)
print(" 100원짜리 ==> %d개" %c100)
print(" 50원짜리  ==> %d개" %c50)
print(" 10원짜리  ==> %d개" %c10)
print(" 바꾸지 못한 잔돈 ==> %d원 \n" %money)
