# -*- coding: utf-8 -*-
"""20250311-python.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1E6UNC7m1Z48dAL9uFZ4eMN_MNIYS5RGO
"""

#Code02-04.py
a= int(input("첫 번째 숫자를 입력하세요 : "))
b= int(input("두 번쨰 숫자를 입력하세요 : "))
result = a+b
print(a, "+", b, "=", result)
result = a-b
print(a, "-", b, "=", result)
result = a*b
print(a, "*", b, "=", result)
result = a/b
print(a, "/", b, "=", result)

