# -*- coding: utf-8 -*-
"""Code03-05

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RmhNdIhaJtNwN5ktbsAiMmZ1aMgqsl_6
"""

#Code03-05.py
## 함수 선언 ##
def myFunc() :
  print('함수를 호출함.')

## 전역 변수 선언 ##
gVar = 100

## 메인 코드 ##
def main() :
  print('메인 함수 부분이 실행됩니다.')
  myFunc()
  print('전역 변수 값:', gVar)

if __name__ == '__main__' :
  main()

#if __name__ == '__main__' :
#  print('메인 함수 부분이 실행됩니다.')
#  myFunc()
#  print('전역 변수 값:', gVar)