# -*- coding: utf-8 -*-
"""20250320-python

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12WR9gD28ObaHK40aHSyWzDMtz2S04Gb0
"""

#Self Study 4-1
#변수 선언
money, c50000, c10000, c5000, c1000 = 0, 0, 0, 0, 0

#메인코드
money = int(input("지폐로 교환할 돈은 얼마? "))

c50000 = money // 50000
money %= 50000

c10000 = money // 10000
money %= 10000

c5000 = money // 5000
money %= 5000

c1000 = money // 1000
money %= 1000

print("\n 50000원짜리 ==> %d개" %c50000)
print(" 10000원짜리 ==> %d개" %c10000)
print(" 5000원짜리  ==> %d개" %c5000)
print(" 1000원짜리  ==> %d개" %c1000)
print(" 지폐로 바꾸지 못한 돈 ==> %d원 \n" %money)
