# -*- coding: utf-8 -*-
"""Self Study 3-1

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RmhNdIhaJtNwN5ktbsAiMmZ1aMgqsl_6
"""

#Self Study 3-1

print("*********")
print(" ******* ")
print("  *****  ")
print("   ***   ")
print("    *    ")
print("   ***   ")
print("  *****  ")
print(" ******* ")
print("*********")